app:
  name: "coze-agent-platform"
  port: "8080"
  mode: "debug" # debug, release

database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  dbname: "coze"

redis:
  host: "localhost"
  port: 6379
  password: "102914"
  db: 0

jwt:
  secret: "coze-agent-secret-key-change-in-production"
  expire: 7200 # seconds (2 hours)

log:
  level: "info" # debug, info, warn, error
  format: "json" # json, text 

# coze:
#   api_url: "https://api.coze.cn"
#   client_id: "1122938180388"
#   private_key: "-----BEGIN PRIVATE KEY-----
# MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgZHBEvYTd8X8J
# QpD6AuxPifKGDcnnwg7wyzI9YtESLd+tNO9EmRUNXdb7a75x10To80Fxo1IlG265
# vRPX80NQBoqxaUIMIPOh4HFSpHyWgzxbWgZcVBIecsZ1rhZAfo11Sjj2DZOmANUX
# KzB7biLy5mAHej9stYU+sjqFdHypnRWodrCTc68KrMkqMoJg8PDDQy8L9Md+HNeP
# pqsftlZo0NgJw6MPB393M7c4NAHhvubxcG9MXUwCBC7vTeYLS3SOrM3GdUpQ+65c
# hrYqt2tMI6Iu8YXfG92q24vjIwKbSVj/Bmi25zNxx6RkWpMd2SyTDDPPRBptzPQf
# 5jIU4HO/AgMBAAECggEAEsrBxqQH0bMuRaj5cHlwM39/nUo3SkKX2omMKNoPkdgz
# GUmW8QwYhdjlS87bYN4ucjayB7zxbmyQ5A0tqoMTc2hYzqF8/gvMT76KuHqSKFZW
# 94MMNLwa5VtgOkB71fGd5EyecOG1V2FIli7WvtdwG9J3FNkzXirEYkyig6law8p2
# q1EeHCSf/KEmcdPGB8GAREj/2kzGU4Ez2e3klmg+0NC7xfyOGa5DRlZDRKUOpVx/
# zXESziavLDbyHV9S5hOqwU4W0Dmd5rAi3/XDIOvbTpsYeEOZo9OtZDzOobufyplV
# RVrF+37aOop+kAvKIkv0xYBJONeYP19CvkkNv74mqQKBgQDcxOTGt9IhDZtzm3C+
# 9O0IH0gzgriNJzmiqP/qm9pW2IIADPIXDf1BqhC0H135A0EBOFnLpDx/wrYXgiSw
# RRbLv0xZH6Qh8ViZ8fJdLzBlHniTrzcEpMwGjmKWilDzsEPRfiQzewynPsuLcZth
# t06xtSWeigRBSj7vkjkSwOfc1wKBgQC5/PcivmJayWcujP/QRgG9rDCWo8UAGh/s
# XaIVeL8AeoCIpehD3Y3m5c6XlD/UNidxEaBkK5IgN5D1027ZE3w6n3B0cOzs86op
# kTc+POQEnNfYoF2sVrCvbEgNnfV24YP93sztBwP7SoPnYx+sJ6z3vhv4KzvYLFKn
# ABJw5pYbWQKBgQCmSdhYphUsuGcjCS4/Z5UyzP1Bb3E7QRR0pP8+4+3uBF7HUvj2
# zJ66WzMBua665eyM0rkwXqEDStKFmo2wCBpHlewYJXEn7/Zg3pFEB0tYnz8LXqr+
# YHMdbRptcfnP1DEBFxaFgGXjg7Ulb4kubThlOqD/bc4Or7IAGg/LRGphOQKBgDmQ
# bf0258Ipq+HgihywTkGiVbeKIKMTcuX5ZP04TgWb5MRmdSjsHctlPTf1Dnxj9nks
# d3QJeES4bgln01skiMKsLmYbvXjpQbVz2KFOv1QeJ0BJAjUg77ab0QFF7n9I9U1R
# 9CM4lKbmPUUUjOz/qq1TDd0VpIQX080UXKDM/ZChAoGBAICWNH8d/7TKsX1mJY4K
# D3+semp+MlQEHQ3h4zikJgOu65CPvmL0gMEcwYZPTrtLFm+iG5bPOXDbIKK4ShIu
# YjNbUBW0BSFI4wocHLj6c4F1p958sSJo6vMMJQA6PiIEn3wWl4Qc0OOa1I8tT1W3
# Hh/8pkpsi4gIq+RHKvS3sqbP
# -----END PRIVATE KEY-----"
#   private_key_file_path: "C:/study/coze/config/private_key.pem"
#   public_key_id: "gbdyFvWh6aMIOxysqMGgEIXjEAvBxWCWp-Nt8QsMptQ"
#   bot_id: "7520462330216579107"

coze:
  api_url: "https://api.coze.cn"
  client_id: "1142499259147"
  private_key: 
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC65VVMwDknri2h
    /bYIpKa38hEvs12rLm4cF5uz9IXJ8EzsxASy6E7RPLra6xk8EuXmnlWdOToVqflb
    lYcBBWYx1uldoMtYOmNYMfkttXln68FqHK7fdpnCiz19b+ggS3FcYkbsIPMq5XQW
    zcaYTsgMEqEkIn0d2edFlBuqPjokG22bWR6UNIF9B0IboYqJYxPv0BDTH2RLi0ia
    5U7uO05PdCAl8Rc9S6zFpr4awQEU4tfc562bFGWq9ZV0muinJYjvbP4TLktxh0bu
    XY/qBEPVZzRWZorxInuEXPSvgMWrR7efjxM/EtGZcrcvCNIp53kJaq6a4Jr7cSsb
    0GvDXbZJAgMBAAECggEAFGwTXFHj3PFkNJ+F2N9vBUoa9SinG1m1N/YfcjRNu0F6
    EmQf9FG8rRHzBBFs/jq9auwRxF6YuX3LjOWjrSmjH16RvQShO6iTqvM4/HToSYIC
    Lj9on2v1BMRUyYRlK8Q6pKLrh4lZMO6GNyiwovt20hTmDU4EeHLTWe/DbyCiF0hF
    JBIqS2cI6IJQbEib24FTzya8/Vetbrkmwv7gHXF5juBuIQkTUK2zSANPI40gdFb9
    Eg5gKY4A5qh8j44rhx7YxVjR6FoGq+2FvnKV9CtIDHPDEi39HV2t8Bg/Z7lx/1qi
    qm5fPdsame93+xl426T5USDcFmFXDHcQEP1liEIhxQKBgQDjr6soDisLhlUuLLzQ
    gH02dXOMIzl7BiXlwwRUcD0lB6URitbLOE8D68qd9B7wZbTJC26cV/OIgdL7BwRr
    SWh/wOgtvQVkymYpF1a8oVuBYaY/0vBo3/YdqfuVbehZWAKA/eODpHCC76I6eC3q
    u4TttXLLM34UPcJgidiv1mnphQKBgQDSIx0ZZvgaXe2AmDHSL/a8YpQQyhPWZlNq
    E7UBKmbnFuyFqB3Zq6uOz1jDqsHF/XqY8lzqw6CcXJt32XCqWDX+MPSSF98QEYj+
    dE5MRcgzeEqjNPc8NoT3SpPdtzGRgFpLiGLVopNZKbM/kuvQd8iiAaS2hczOufYE
    mJ4/SzRy9QKBgQCTGJbXFfAxTeQSJM0HVzuNx2uTCd7E4D/zpH5Tnv+hwMKgBram
    LAbAXcFVMrYaUVru1/fqAdhQRK9thicQuShOAO7/PbMSXsCJo45h500a1V92tGyl
    FKwIlhz3eT43GmjjtSMblU0rCm4goCvqDqPefu9e4DGAGjZN8ECRuVBLkQKBgQCe
    Opp6ujIviHKB1hgNsNgVWhUr3z24vywoP9aXnhoGABjxO3neoYl462BnVXi7YPaj
    nDui+tNBaeoXAL/5RJrDYJGIQDlSnCGPmHwsqo7pUrbA1e0khdjxbFKTLJJCgWd8
    YKIrQ1O4W9IBGNxACTIl6x7f4TgqoZRCOblO544C0QKBgQCFCsp2tWNhnbPEK9jU
    bktUOxY7cmOd+Ae9L0HYoentrBUREQKt+9p+/GuAXN/bdxcWGzTiiFi/FzDaiVtO
    AcuhFufEadFm9XFK3fgGAnatcSB56wM3eENDkh+5fThreWu5ELeQCypionopJh6C
    n3RdNf1rfmvIKOkEmmxoG2e1vw==
    -----END PRIVATE KEY-----
  private_key_file_path: "C:/study/coze/config/private_key2.pem"
  public_key_id: "jPEFNYsuk9cFkbq28H9181kM3LAt_17ILryf2Nl7aPk"
  bot_id: "7522022174069588004"